name: bump-pv
on:
  repository_dispatch:
    types: [bump-pv]
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: +1
        run: |
          old=$(cat docs/pv.txt | tr -d '[:space:]')
          old=${old:-0}
          new=$((old + 1))
          echo $new > docs/pv.txt
          echo "new=$new" >> $GITHUB_ENV
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump pv â†’ ${{ env.new }}"
          file_pattern: "docs/pv.txt"
