name: bump-pv
on:
  repository_dispatch:
    types: [bump-pv]
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          old=$(cat docs/pv.txt)
          new=$((old + 1))
          echo $new > docs/pv.txt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump pv â†’ ${{ env.new }}"
