name: free-api
on:
  repository_dispatch:
    types: [issue-open]
  workflow_dispatch:

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Issue
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.LONG_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '${{ github.event.client_payload.body }}'
